Repository swsnu/swpp2021-team9, pull requests merged in 2021-11, with the labels that each got.

#14 [Frontend] Create Song Page design
  frontend/src/app/containers/CreateSongPage/index.test.tsx
  frontend/src/app/containers/CreateSongPage/index.tsx
  frontend/src/app/index.tsx
  frontend/src/index.css
  frontend/src/index.tsx
  frontend/src/styles/global-styles.ts
  frontend/tailwind.config.js
Labels: enhancement

#18 [Frontend] header for mid
  frontend/package.json
  frontend/src/app/components/Search/Search.css
  frontend/src/app/components/Search/index.test.tsx
  frontend/src/app/components/Search/index.tsx
  frontend/src/app/containers/MainPage/index.tsx
  frontend/src/app/helper/Hooks.test.ts
  frontend/src/app/helper/Hooks.ts
  frontend/src/app/helper/Player.test.ts
  frontend/src/app/helper/Player.ts
  frontend/src/app/helper/TrackPlayer.ts
  frontend/src/app/helper/mockPlayList.ts
  frontend/src/app/wrapper/Header/index.test.tsx
  frontend/src/app/wrapper/Header/index.tsx
  frontend/src/app/wrapper/PlayerBar/index.test.tsx
  frontend/src/app/wrapper/PlayerBar/index.tsx
  frontend/src/app/wrapper/Wrapper.css
  frontend/src/app/wrapper/index.test.tsx
  frontend/src/app/wrapper/index.tsx
  frontend/src/app/wrapper/slice/index.test.ts
  frontend/src/app/wrapper/slice/index.ts
  frontend/src/app/wrapper/slice/selectors.ts
  frontend/src/res/loading.gif
  frontend/src/res/logo.svg
  frontend/src/res/next-button.svg
  frontend/src/res/pause-button.svg
  frontend/src/res/play-button.svg
  frontend/src/res/prev-button.svg
  frontend/src/res/search-icon.svg
  frontend/src/res/thumb_down_black_filled.svg
  frontend/src/res/thumb_down_black_outlined.svg
  frontend/src/res/thumb_up_black_filled.svg
  frontend/src/res/thumb_up_black_outlined.svg
  frontend/src/styles/Landie.svg
  frontend/src/types/RootState.ts
  frontend/src/types/types.d.ts
  frontend/yarn.lock
Labels: enhancement

#19 [Frontend] Song Page design
  frontend/package.json
  frontend/src/app/containers/SongPage/CombinationArea/AddCoverButton.tsx
  frontend/src/app/containers/SongPage/CombinationArea/AddedCoverList.tsx
  frontend/src/app/containers/SongPage/CombinationArea/index.tsx
  frontend/src/app/containers/SongPage/SongInfo.tsx
  frontend/src/app/containers/SongPage/TopCombination.tsx
  frontend/src/app/containers/SongPage/TopCover.tsx
  frontend/src/app/containers/SongPage/dummy.ts
  frontend/src/app/containers/SongPage/getIcon.ts
  frontend/src/app/containers/SongPage/index.test.tsx
  frontend/src/app/containers/SongPage/index.tsx
  frontend/src/app/containers/SongPage/slice/index.test.ts
  frontend/src/app/containers/SongPage/slice/index.ts
  frontend/src/app/containers/SongPage/slice/selectors.ts
  frontend/src/index.css
  frontend/src/types/RootState.ts
  frontend/src/types/types.d.ts
  frontend/yarn.lock
Labels: enhancement

#20 Frontend/create cover page
  frontend/declarations.d.ts
  frontend/package.json
  frontend/src/app/containers/CreateCoverPage/AudioVisualizer.tsx
  frontend/src/app/containers/CreateCoverPage/Canvas.tsx
  frontend/src/app/containers/CreateCoverPage/CustomPlayer.tsx
  frontend/src/app/containers/CreateCoverPage/Waveform.tsx
  frontend/src/app/containers/CreateCoverPage/index.ts
  frontend/src/app/containers/CreateCoverPage/slice/index.ts
  frontend/src/app/containers/CreateCoverPage/step1.tsx
  frontend/src/app/containers/CreateCoverPage/step2.test.tsx
  frontend/src/app/containers/CreateCoverPage/step2.tsx
  frontend/src/app/containers/CreateCoverPage/step3.test.tsx
  frontend/src/app/containers/CreateCoverPage/step3.tsx
  frontend/src/app/containers/SongPage/CombinationArea/index.tsx
  frontend/src/app/index.tsx
  frontend/src/types/RootState.ts
  frontend/src/utils/urls.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: enhancement

#22 [Frontend] Main Page, Search Result Page
  .secrets
  frontend/src/app/components/Album/Album.css
  frontend/src/app/components/Album/AlbumImage.png
  frontend/src/app/components/Album/AlbumImage0.jpg
  frontend/src/app/components/Album/AlbumImage1.jpg
  frontend/src/app/components/Album/AlbumImage2.jpg
  frontend/src/app/components/Album/AlbumImage3.jpg
  frontend/src/app/components/Album/AlbumImage4.jpg
  frontend/src/app/components/Album/AlbumImage5.jpg
  frontend/src/app/components/Album/index.test.tsx
  frontend/src/app/components/Album/index.tsx
  frontend/src/app/components/ResultLine/index.test.tsx
  frontend/src/app/components/ResultLine/index.tsx
  frontend/src/app/containers/MainPage/dummy.ts
  frontend/src/app/containers/MainPage/index.tsx
  frontend/src/app/containers/SearchResultPage/dummy.ts
  frontend/src/app/containers/SearchResultPage/index.test.tsx
  frontend/src/app/containers/SearchResultPage/index.tsx
  frontend/src/types/types.d.ts
Labels: enhancement

#24 [Frontend] Refactor create cover page
  frontend/declarations.d.ts
  frontend/src/app/containers/CreateCoverPage/Waveform.tsx
  frontend/src/app/containers/CreateCoverPage/step1.tsx
  frontend/src/app/containers/SongPage/CombinationArea/index.tsx
  frontend/src/app/index.tsx
  frontend/tsconfig.json
Labels: enhancement

#11 [Feature] Backend/makemodels
  .travis.yml
  README.md
  backend/app/band/migrations/0001_initial.py
  backend/app/band/migrations/0002_initial.py
  backend/app/band/models.py
  backend/app/band/tests.py
  backend/app/band/views.py
  backend/app/bandcruit/settings.py
  backend/app/user/managers.py
  backend/app/user/migrations/0001_initial.py
  backend/app/user/models.py
  backend/app/user/tests.py
  backend/app/user/views.py
  backend/requirements.txt
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/containers/CoverPage/index.test.tsx
  frontend/src/app/containers/CreateCoverPage/step1.test.tsx
  frontend/src/app/containers/CreateCoverPage/step2.test.tsx
  frontend/src/app/containers/CreateCoverPage/step3.test.tsx
  frontend/src/app/containers/CreateSongPage/index.test.tsx
  frontend/src/app/containers/CreateSongPage/index.tsx
  frontend/src/app/containers/MainPage/index.test.tsx
  frontend/src/app/containers/MainPage/index.tsx
  frontend/src/app/containers/MainPage/slice/index.test.ts
  frontend/src/app/containers/MainPage/slice/selectors.ts
  frontend/src/app/containers/ProfilePage/index.test.tsx
  frontend/src/app/containers/SearchResultPage/index.test.tsx
  frontend/src/app/containers/SignInPage/index.test.tsx
  frontend/src/app/containers/SignUpPage/index.test.tsx
  frontend/src/app/containers/SongPage/index.test.tsx
  frontend/src/app/index.test.tsx
  frontend/src/app/index.tsx
  frontend/src/app/wrapper/index.tsx
  frontend/tsconfig.json
  frontend/yarn.lock
  sonar-project.properties
Labels: enhancement

#29 typo in README.md
  README.md
Labels: bug

#28 Frontend/header/style
  frontend/package.json
  frontend/src/app/components/Search/Search.css
  frontend/src/app/components/Search/index.tsx
  frontend/src/app/containers/SearchResultPage/index.tsx
  frontend/src/app/wrapper/Header/index.tsx
  frontend/src/app/wrapper/PlayerBar/index.tsx
  frontend/src/app/wrapper/Wrapper.css
  frontend/src/app/wrapper/index.tsx
  frontend/src/res/next-button.svg
  frontend/src/res/pause-button.svg
  frontend/src/res/play-button.svg
  frontend/src/res/prev-button.svg
  frontend/src/res/search-icon.svg
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: enhancement

#33 [Frontend] MainPage Album style
  frontend/src/app/components/Album/index.test.tsx
  frontend/src/app/components/Album/index.tsx
  frontend/src/app/containers/MainPage/index.test.tsx
  frontend/src/app/containers/MainPage/index.tsx
  frontend/src/app/containers/MainPage/slice/index.test.ts
  frontend/src/app/containers/MainPage/slice/index.ts
  frontend/src/app/containers/MainPage/slice/selectors.ts
  frontend/src/app/helper/Player.ts
  frontend/src/types/RootState.ts
Labels: enhancement

#37 [Frontend] wrapper test code
  frontend/src/app/helper/Player.test.ts
  frontend/src/app/helper/Player.ts
  frontend/src/app/helper/TrackPlayer.test.ts
  frontend/src/app/helper/TrackPlayer.ts
  frontend/src/app/wrapper/Header/index.tsx
  frontend/src/app/wrapper/PlayerBar/index.test.tsx
  frontend/src/app/wrapper/PlayerBar/index.tsx
  frontend/src/app/wrapper/index.test.tsx
  frontend/src/app/wrapper/index.tsx
Labels: enhancement

#40 [Frontend] Song Page Test
  frontend/src/app/components/Dropdown/CoverDropdown/index.test.tsx
  frontend/src/app/components/Dropdown/CoverDropdown/index.tsx
  frontend/src/app/components/Dropdown/InstrumentDropdown/index.test.tsx
  frontend/src/app/components/Dropdown/InstrumentDropdown/index.tsx
  frontend/src/app/containers/SongPage/CombinationArea/AddCoverButton.tsx
  frontend/src/app/containers/SongPage/CombinationArea/AddedCoverList.tsx
  frontend/src/app/containers/SongPage/SongInfo.test.tsx
  frontend/src/app/containers/SongPage/SongInfo.tsx
  frontend/src/app/containers/SongPage/TopCombination.test.tsx
  frontend/src/app/containers/SongPage/TopCombination.tsx
  frontend/src/app/containers/SongPage/TopCover.test.tsx
  frontend/src/app/containers/SongPage/TopCover.tsx
  frontend/src/app/containers/SongPage/index.test.tsx
  frontend/src/app/containers/SongPage/index.tsx
  frontend/src/app/containers/SongPage/index_functional.test.tsx
  frontend/src/app/containers/SongPage/slice/index.test.ts
  frontend/src/app/containers/SongPage/slice/index.ts
  frontend/src/utils/getIcon.ts
Labels: enhancement

#39 [Frontend] Main Page, Search Result Page test code
  frontend/src/app/components/Album/index.test.tsx
  frontend/src/app/components/Album/index.tsx
  frontend/src/app/components/ResultLine/index.test.tsx
  frontend/src/app/components/ResultLine/index.tsx
  frontend/src/app/containers/MainPage/index.test.tsx
  frontend/src/app/containers/MainPage/index.tsx
  frontend/src/app/containers/SearchResultPage/dummy.ts
  frontend/src/app/containers/SearchResultPage/index.test.tsx
  frontend/src/app/containers/SearchResultPage/index.tsx
Labels: enhancement

#31 [Frontend] Frontend/create cover page test
  frontend/src/app/components/CreateCover/VideoPreview.test.tsx
  frontend/src/app/components/CreateCover/VideoPreview.tsx
  frontend/src/app/components/CreateCover/WaveformSetButton.test.tsx
  frontend/src/app/components/CreateCover/WaveformSetButton.tsx
  frontend/src/app/components/CreateCover/YoutubePlayer.test.tsx
  frontend/src/app/components/CreateCover/YoutubePlayer.tsx
  frontend/src/app/containers/CreateCoverPage/AudioVisualizer.tsx
  frontend/src/app/containers/CreateCoverPage/Canvas.tsx
  frontend/src/app/containers/CreateCoverPage/Waveform.tsx
  frontend/src/app/containers/CreateCoverPage/index.ts
  frontend/src/app/containers/CreateCoverPage/slice/index.test.ts
  frontend/src/app/containers/CreateCoverPage/slice/index.ts
  frontend/src/app/containers/CreateCoverPage/slice/selectors.ts
  frontend/src/app/containers/CreateCoverPage/step1.test.tsx
  frontend/src/app/containers/CreateCoverPage/step1.tsx
  frontend/src/app/containers/CreateCoverPage/step2.test.tsx
  frontend/src/app/containers/CreateCoverPage/step2.tsx
Labels: enhancement

#41 [Frontend] jest collect coverage setting
  frontend/package.json
Labels: invalid

#48 Add README instructions
  README.md
  frontend/README.md
Labels: documentation

#46 [Backend] views, urls
  backend/.pylintrc
  backend/app/band/admin.py
  backend/app/band/models.py
  backend/app/band/serializers.py
  backend/app/band/tests.py
  backend/app/band/urls.py
  backend/app/band/views.py
  backend/app/band/views/__init__.py
  backend/app/band/views/combination_views.py
  backend/app/band/views/cover_views.py
  backend/app/band/views/instrument_views.py
  backend/app/band/views/song_views.py
  backend/app/band/views/test_combination.py
  backend/app/band/views/test_cover.py
  backend/app/band/views/test_song.py
  backend/app/band/views/test_token.py
  backend/app/band/views/token_views.py
  backend/app/bandcruit/settings.py
  backend/app/bandcruit/urls.py
  backend/app/user/serializers.py
  backend/app/user/tests.py
  backend/app/user/urls.py
  backend/app/user/views.py
  backend/requirements.txt
  sonar-project.properties
Labels: enhancement

#52 [Backend] Fix model blank options
  backend/app/band/models.py
  backend/app/user/models.py
Labels: bug

#54 [Frontend] Get Youtube Thumbnail link
  frontend/src/api/dummy.ts
  frontend/src/app/components/Album/AlbumImage0.jpg
  frontend/src/app/components/Album/AlbumImage1.jpg
  frontend/src/app/components/Album/AlbumImage2.jpg
  frontend/src/app/components/Album/AlbumImage3.jpg
  frontend/src/app/components/Album/AlbumImage4.jpg
  frontend/src/app/components/Album/AlbumImage5.jpg
  frontend/src/app/components/Album/index.tsx
  frontend/src/app/components/Dropdown/InstrumentDropdown/index.tsx
  frontend/src/app/containers/CoverPage/index.tsx
  frontend/src/app/containers/MainPage/index.tsx
  frontend/src/app/containers/SongPage/CombinationArea/AddedCoverList.tsx
  frontend/src/app/containers/SongPage/SongInfo.tsx
  frontend/src/app/containers/SongPage/index.tsx
  frontend/src/utils/getIcon.ts
  frontend/src/utils/imageTools.ts
Labels: enhancement
